title: Solving for Homelessness
description: Insert description here - Slate is a theme for GitHub Pages.
show_downloads: false
google_analytics:
remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme 
